 insert into fabricante values (nextval('fabricante_sequence'), 'Apple Inc.', 'BR')
 insert into fabricante values (nextval('fabricante_sequence'), 'Samsung Inc.', 'BR')
 insert into modelo values (nextval('modelo_sequence'), 'AppleCar')
 insert into modelo values (nextval('modelo_sequence'), 'SamsungTank')
 insert into carro values (nextval('carro_sequence'), 'PARTICULAR', 'AAAA123', 'COMBUSTAO', 1, 1)
 insert into carro values (nextval('carro_sequence'), 'PARTICULAR', 'AAAA124', 'COMBUSTAO', 1, 1)